"""

Revision ID: 5bbacf14ac89
Revises: 4882b2bdd77f
Create Date: 2026-03-16 22:14:38.617961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbacf14ac89'
down_revision: Union[str, None] = '4882b2bdd77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('tension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'tension')
    # ### end Alembic commands ###
