"""update diary model remove title add mood

Revision ID: 862a2c5831e7
Revises: 26cb09b31fe3
Create Date: 2026-02-16 16:50:49.651182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862a2c5831e7'
down_revision: Union[str, None] = '26cb09b31fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('mood', sa.String(length=50), nullable=True))
    op.drop_column('diaries', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('diaries', 'mood')
    # ### end Alembic commands ###
