"""add tension field to diary

Revision ID: 8c1f39b2edee
Revises: 5bbacf14ac89
Create Date: 2026-03-17 00:03:44.428155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1f39b2edee'
down_revision: Union[str, None] = '5bbacf14ac89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('tension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'tension')
    # ### end Alembic commands ###
